version: "2.13"
services:
  backend:
    build:
      context: ./src
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    container_name: nba
    networks:
      - nba-app-network

networks:
  nba-app-network:
    driver: bridge
