version: "3.8"
services:
  backend:
    build:
      context: ./src
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    container_name: nba
   

  frontend:
    build:
      context: ./Frontend
      dockerfile: frontend.Dockerfile
    ports:
      - "8501:8501"
    container_name: nba-frontend
   

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
  python:
    build: 
      context: ./DB
      dockerfile: db.Dockerfile
    ports:
      - "8001:8001"
    links:
      - mongodb
   


