version: "3.8"
services:
  backend:
    build:
      context: ./src
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    container_name: nba
    networks:
      - my_network

  frontend:
    build:
      context: ./Frontend
      dockerfile: frontend.Dockerfile
    ports:
      - "8501:8501"
    container_name: nba-frontend
    networks:
      - my_network

  db:
    image: mongo:3.6.8
    ports:
      - "27017:27017"
    container_name: nba-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ron_pinto
      MONGO_INITDB_ROOT_PASSWORD: Aa123456
      MONGO_INITDB_DATABASE: icons
    command: --bind_ip_all
    networks:
      - my_network

networks:
  my_network:
