version: "3.8"
services:
  backend:
    build:
      context: ./src
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    container_name: nba
   

  frontend:
    build:
      context: ./Frontend
      dockerfile: frontend.Dockerfile
    ports:
      - "8501:8501"
    container_name: nba-frontend
 

  db:
  image: mongo
  ports:
  - "27017:27017"
  container_name: nba-mongodb

